sudo: required
services:
  - docker
language: node_js
node_js:
  - stable
before_install:
  - git clone https://github.com/aa8y/dave.git
install:
  - npm install -g dave/
before_script:
  - dave build
script:
  - dave test
after_success:
  - docker login -u aa8y -p "$DOCKER_PASSWORD"
  - dave push
ignore:
  - "*.md"
