sudo: required
services:
  - docker
language: node_js
node_js:
  - stable
before_install:
  - mkdir dave
  - wget -q -O- https://github.com/aa8y/dave/archive/v0.1.0.tar.gz | tar -xz --strip 1 -C dave/
install:
  - npm install -g dave/
before_script:
  - dave build
script:
  - dave test
after_success:
  - docker login -u aa8y -p "$DOCKER_PASSWORD"
  - dave push
ignore:
  - "*.md"
